# Site
name: "Around the World in 200 Dishes"
title: "Around the World in 200 Dishes"
description: "Recipies from every country."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /200dishes
include: ["_pages"]
permalink: /:title/

# Authors
authors:

  rra:
    name: RRA
    display_name: RRA    
    avatar: 'assets/images/avatar.png'
    email: rra.iitk@gmail.com
    web: http://www.rishavrajagarwal.com
    instagram: https://instagram.com/yolo.solo
    description: "Likes cooking food, origami and playing the guitar. In his free time, he does computer vision. "

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
